version: "3.5"

services:
#  nats:
#    image: 'nats:0.8.0'
#    entrypoint: "/gnatsd -DV"
#    expose:
#      - "4222"
#    ports:
#      - "4222:4222"
#    hostname: nats-server
  postgres:
    build: ./docker/postgresql
    container_name: fakesms_psql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - ./.env
    volumes:
      - fakesms_psql_data:/var/lib/postgresql/data:delegated
    networks:
      - fakesms


volumes:
  fakesms_psql_data:
    driver: local


networks:
  fakesms:
    name: fakesms
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.22.0/24
